#!/usr/bin/env bash
# Regenerate src/bindings.rs from the committed libvpx headers.
#
#   ./gen-bindings.sh            # rewrite src/bindings.rs
#   ./gen-bindings.sh --check    # fail if src/bindings.rs is not what the headers say
#
# Why generated and committed rather than generated at build time: bindgen needs libclang, and
# a `-sys` crate whose entire selling point is that a consumer needs no C toolchain cannot then
# require an LLVM installation to build. RustDesk generates its vpx bindings in a build script
# and therefore requires libclang of everyone who builds it; this does not.
#
# One file for every target, and that is sound rather than lucky: bindgen emits
# `::std::os::raw::c_int` and `c_char` as *aliases*, which each target resolves for itself, so
# the same source is correct on aarch64 (where c_char is unsigned) and on x86_64 (where it is
# signed).
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$here"
# shellcheck source-path=SCRIPTDIR
# shellcheck source=../../libvpx.env
. ../../libvpx.env

# Pinned, because bindgen's output is not stable across its own versions — field ordering, the
# shape of the generated enum constants and the layout tests have all changed between releases.
# An unpinned generator turns `--check` into a test of which bindgen the runner happened to
# install.
BINDGEN_VERSION=0.72.1

out=src/bindings.rs

command -v bindgen >/dev/null 2>&1 || {
  echo "bindgen is not installed. cargo install bindgen-cli --version $BINDGEN_VERSION --locked" >&2
  exit 1
}
actual_version="$(bindgen --version | awk '{print $2}')"
[ "$actual_version" = "$BINDGEN_VERSION" ] || {
  echo "bindgen $actual_version is installed but this file is generated with $BINDGEN_VERSION" >&2
  echo "  cargo install bindgen-cli --version $BINDGEN_VERSION --locked --force" >&2
  exit 1
}

generate() {
  # Layout checks kept, deliberately — no `--no-layout-tests`. They are what makes committing
  # *one* bindings.rs for three targets an assertion rather than an assumption, and it matters
  # more here than in a codec with a small surface: `vpx_codec_enc_cfg_t` is a 60-field struct
  # that a consumer fills in by name and libvpx reads by offset, and
  # `vpx_codec_enc_init_ver`'s ABI version argument does not catch a Rust-side layout that
  # disagrees with the archive's.
  #
  # bindgen 0.72 emits these as `const _: () = { ["Size of X"][size_of::<X>() - N]; }`, which
  # fails at **compile** time rather than as a `#[test]` — better than a test, since a consumer
  # who never runs the test suite still cannot build against a struct that packs differently on
  # their target.
  #
  # `--default-enum-style consts` rather than rustified enums: libvpx's control ids and error
  # codes are C enums that its own API passes as `int`, and several — `vpx_codec_err_t` in
  # particular — are compared against values a future libvpx may extend. A Rust enum with an
  # unlisted discriminant is undefined behaviour; a constant is a number.
  #
  # `--rust-target` pinned for the same reason the bindgen version is, and it is the one flag
  # that decides this crate's MSRV: bindgen defaults to the newest Rust it knows about (1.82 as
  # of 0.72.1), and from 1.82 it emits `unsafe extern "C" { … }` blocks, which do not parse on
  # an older compiler. Naming 1.81 keeps the declared `rust-version` a property of this file
  # rather than of whichever bindgen the generating machine had.
  bindgen wrapper.h \
    --rust-target 1.81 \
    --allowlist-file '.*/vpx/.*' \
    --default-enum-style consts \
    --no-doc-comments \
    --raw-line "// @generated by gen-bindings.sh from the libvpx $LIBVPX_VERSION headers in" \
    --raw-line "// include/vpx/ — do not edit. Regenerate with bindgen $BINDGEN_VERSION." \
    --raw-line "//" \
    --raw-line "// \`--allowlist-file\` restricts this to items declared by libvpx's own headers." \
    --raw-line "// Without it the output also carries whatever <stddef.h> and <stdint.h> declare" \
    --raw-line "// on the generating machine, which is one libc's idea of them — portable in" \
    --raw-line "// practice because they are bare aliases, but not something to ship on that" \
    --raw-line "// reasoning." \
    --raw-line "#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case)]" \
    -- -I include
}

if [ "${1:-}" = "--check" ]; then
  # Compared as text rather than by regenerating in place and asking git: this has to work in a
  # CI job that has not necessarily checked out with a clean tree, and the diff is worth
  # printing either way.
  tmp="$(mktemp)"
  trap 'rm -f "$tmp"' EXIT
  generate > "$tmp"
  if diff -u "$out" "$tmp"; then
    echo "$out matches the committed libvpx $LIBVPX_VERSION headers"
    exit 0
  fi
  echo "$out is stale — run gen-bindings.sh" >&2
  exit 1
fi

# Generated beside the target and renamed onto it, rather than redirected straight into it: a
# `> "$out"` truncates the committed bindings *before* bindgen runs, so a failed generation —
# a missing header, a clang that cannot parse one — leaves the crate with an empty bindings.rs
# and no way back except git.
tmp="$(mktemp "$out.XXXXXX")"
trap 'rm -f "$tmp"' EXIT
generate > "$tmp"
chmod 644 "$tmp"
mv "$tmp" "$out"
trap - EXIT
echo "wrote $out ($(wc -l < "$out" | tr -d ' ') lines from libvpx $LIBVPX_VERSION)"
